// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jexfkzvxvxiljdzqpkbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpleGZrenZ4dnhpbGpkenFwa2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDQ4NTcsImV4cCI6MjA2MDYyMDg1N30.sale_JuLaJmdw0lwhi1L__2oH5izN7BOsAAgjhJ0Dp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);